DROP TABLE LOCATION;

CREATE TABLE LOCATION (
ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
NAME VARCHAR2(255) DEFAULT NULL,
STREET_ADDRESS VARCHAR2(255) DEFAULT NULL,
CITY VARCHAR2(255) DEFAULT NULL,
STATE VARCHAR2(255) DEFAULT NULL,
ZIPCODE VARCHAR2(255) DEFAULT NULL,
STREET_ADDRESS VARCHAR2(255) DEFAULT NULL,
STREET_ADDRESS VARCHAR2(255) DEFAULT NULL,
PRIMARY KEY (ID));

DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;